### ISSUE TITLE
hello-go fails to run in alpine

### ISSUE THREAD

**Issue by welsh1lad** [geerlingguy/ansible-for-kubernetes#45]
Chapter 1 Page six build docker container
first line in the Dockerfile 
FROM golang:1-alpine as build 

 With the command 
docker build -t hello-go  .

 Output
Error parsing reference: "golang:1-alpine as build" is not a valid repository/tag: invalid reference format

**Comment by welsh1lad** [comment]
Resolved 👍
 Reason for this was that docker-ce was not installed , but docker . this dose not support AS build
    It is stated in the book to install docker-ce 
on centos 7
 remove current docker install 
   227 yum remove docker
   228 yum remove docker-common
  229  yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  230  yum install -y docker-ce
  231  yum-config-manager --enable docker-ce-edge
  232  yum-config-manager --enable docker-ce-test
  233  systemctl start docker

  You can now run multistage builds

**Comment by geerlingguy** [comment]
@welsh1lad - Ah, glad you could get that resolved. And yeah, it's a bit annoying that `docker` doesn't work since it's quite old but is still present in the default repos on many distro versions that are still in use!
